[package]
name = "phcalc-egui"
version = "0.1.0"
authors = ["Peter Berck <peter@berck.se>"]
license = "MIT OR Apache-2.0"
edition = "2021"
rust-version = "1.81"
publish = false

[dependencies]
eframe = "0.31.1"
egui = "0.31.1"
env_logger = "0.11.8"
pinhole = { path = "../pinhole" }
